//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquaMai.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AquaMai.Core.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using AquaMai CI build version. This version is built from the latest mainline code and may contain undocumented configuration changes or potential issues..
        /// </summary>
        public static string CiBuildAlertContent {
            get {
                return ResourceManager.GetString("CiBuildAlertContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Notice: Test Version.
        /// </summary>
        public static string CiBuildAlertTitle {
            get {
                return ResourceManager.GetString("CiBuildAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded!.
        /// </summary>
        public static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors detected while loading!
        ///- Are you using a modified Assembly-CSharp.dll, which will cause inconsistent functions and cannot find the functions that need to be modified
        ///- Check for conflicting mods, or enabled incompatible options.
        /// </summary>
        public static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string MarkRepeatEnd {
            get {
                return ResourceManager.GetString("MarkRepeatEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string MarkRepeatStart {
            get {
                return ResourceManager.GetString("MarkRepeatStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aime reader error.
        /// </summary>
        public static string NetErrIsAliveAimeReader {
            get {
                return ResourceManager.GetString("NetErrIsAliveAimeReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aime server error.
        /// </summary>
        public static string NetErrIsAliveAimeServer {
            get {
                return ResourceManager.GetString("NetErrIsAliveAimeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server communication error.
        /// </summary>
        public static string NetErrIsAliveServer {
            get {
                return ResourceManager.GetString("NetErrIsAliveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data download not success.
        /// </summary>
        public static string NetErrWasDownloadSuccessOnce {
            get {
                return ResourceManager.GetString("NetErrWasDownloadSuccessOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游玩次数：{0}.
        /// </summary>
        public static string PlayCount {
            get {
                return ResourceManager.GetString("PlayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSS+ =&gt; DXRating += {0}.
        /// </summary>
        public static string RatingUpWhenSSSp {
            get {
                return ResourceManager.GetString("RatingUpWhenSSSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat end time cannot be less than repeat start time.
        /// </summary>
        public static string RepeatEndTimeLessThenStartTime {
            get {
                return ResourceManager.GetString("RepeatEndTimeLessThenStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Not Set.
        /// </summary>
        public static string RepeatNotSet {
            get {
                return ResourceManager.GetString("RepeatNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string RepeatReset {
            get {
                return ResourceManager.GetString("RepeatReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Set.
        /// </summary>
        public static string RepeatStartEndSet {
            get {
                return ResourceManager.GetString("RepeatStartEndSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Start Set.
        /// </summary>
        public static string RepeatStartSet {
            get {
                return ResourceManager.GetString("RepeatStartSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set repeat start time first.
        /// </summary>
        public static string RepeatStartTimeNotSet {
            get {
                return ResourceManager.GetString("RepeatStartTimeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving... Do not exit the game.
        /// </summary>
        public static string SavingDontExit {
            get {
                return ResourceManager.GetString("SavingDontExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek &lt;&lt;.
        /// </summary>
        public static string SeekBackward {
            get {
                return ResourceManager.GetString("SeekBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek &gt;&gt;.
        /// </summary>
        public static string SeekForward {
            get {
                return ResourceManager.GetString("SeekForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Skipping incompatible patch: {0}.
        /// </summary>
        public static string SkipIncompatiblePatch {
            get {
                return ResourceManager.GetString("SkipIncompatiblePatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed -.
        /// </summary>
        public static string SpeedDown {
            get {
                return ResourceManager.GetString("SpeedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Reset.
        /// </summary>
        public static string SpeedReset {
            get {
                return ResourceManager.GetString("SpeedReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed +.
        /// </summary>
        public static string SpeedUp {
            get {
                return ResourceManager.GetString("SpeedUp", resourceCulture);
            }
        }
    }
}
