常用:
  - General
  - GameSystem.SinglePlayer
  - GameSystem.DisableTimeout
  - GameSystem.QuickRetry
  - UX.OneKeyEntryEnd
  - UX.OneKeyRetrySkip
  - GameSystem.TouchToButtonInput
  - GameSystem.TestProof
  - GameSettings.CreditConfig
  - Utils.FreedomTimer

控制器输入:
  - GameSystem.AdxHidInput
  - GameSystem.MaimollerIO
  - GameSystem.PdxTouch
  - Tweaks.ResetTouch
  - UX.CustomFnToKeyboard

输入设置:
  - GameSystem.KeyMap
  - GameSettings.TouchSensitivity
  - GameSystem.ExteraMouseInput

判定:
  - GameSettings.JudgeAdjust
  - UX.JudgeAccuracyInfo
  - Utils.UnstableRate
  - Utils.DisplayTouchInGame
  - Fancy.GamePlay.JudgeDisplay4B
  - UX.PracticeMode

显示:
  - GameSystem.Window
  - Utils.ScreenPositionAdjust
  - Utils.DisplayFrameRate

音频:
  - GameSystem.Sound
  - GameSystem.SoundRouting
  - GameSystem.HeadphoneVolumeMultiply
  - GameSystem.VolumeSync
  - Utils.MoveAnswerSound

其他硬件:
  - GameSystem.CustomCameraId
  - Tweaks.LedBrightnessControl
  - UX.DisableLightOutGame
  - Utils.LedOffOnQuit
  - GameSystem.OldCabLightBoardSupport
  - GameSystem.LightBoardPort
  - GameSystem.TouchPanelPort
  - GameSystem.TouchPanelBaudRate
  - UX.HardwareAlert

解锁与省时:
  - GameSystem.Unlock
  - Tweaks.TimeSaving.IWontTapOrSlideVigorously
  - Tweaks.TimeSaving.EntryToMusicSelection
  - Tweaks.TimeSaving.SkipEventInfo
  - Tweaks.TimeSaving.SkipTrackStart
  - Tweaks.TimeSaving.ExitToSave
  - Tweaks.TimeSaving.SkipGoodbyeScreen
  - UX.QuickEndPlay
  - UX.OneKeyEntryEnd
  - UX.OneKeyRetrySkip

选曲界面:
  - UX.HideSelfMadeCharts
  - UX.SelectionDetail

美化:
  - Fancy.GamePlay.HideHanabi
  - GameSystem.Assets.Fonts
  - Fancy.CustomLogo
  - Fancy.CustomPlaceName
  - Fancy.CustomVersionString
  - Fancy.CustomCreditsString
  - Fancy.RandomBgm
  - Fancy.CustomSkins
  - Fancy.CustomButton
  - Fancy.DemoMaster
  - Fancy.GamePlay.AlignCircleSlideJudgeDisplay
  - Fancy.GamePlay.SlideArrowAnimation
  - Fancy.GamePlay.SlideFadeInTweak
  - Fancy.GamePlay.SlideLayerReverse
  - UX.FestaControl
  - Fancy.CustomIntroCinematic

调试工具:
  - Utils.AntiLag
  - Tweaks.LockFrameRate
  - Utils.LogUserId
  - Utils.LogNetworkRequests

高级设置:
  - Fancy.HideMask
  - Tweaks.TimeSaving.CheckSkip
  - Utils.InstantQuit
  - Fancy.Triggers

过新过热（实验性）:
  - Fancy.SetFade
  - Fancy.CustomTrackStartDiff
  - Fancy.GamePlay.BreakSlideJudgeBlink
  - Fancy.GamePlay.CustomNoteTypes
  - Fancy.GamePlay.DisableTrackStartTabs
  - Fancy.GamePlay.FanJudgeFlip
  - Fancy.GamePlay.RealisticRandomJudge
  - Fancy.GamePlay.TrackStartProcessTweak
  - Fancy.GamePlay.FixJudgeTouchHoldInNormalArea
  - Fancy.GamePlay.ReviveFinaleVSlide
  - Fancy.GamePlay.TapInHoldFix
  - Fancy.TrackCamouflage
  - Fancy.ResourcesOverride

不建议关闭:
  - UX.ImmediateSave
  - GameSystem.Assets.LoadAssetBundleWithoutManifest
  - GameSystem.Assets.LoadLocalImages
  - GameSystem.Assets.MovieLoader
  - GameSystem.Assets.IgnoreLoadFailedAssetBundle
  - GameSystem.OptionLoadFix
  - Tweaks.SkipUserVersionCheck
  - UX.DontRuinMyAccount
  - GameSystem.AddPlayCountWhenQuickRetry
  - UX.FixTrackNumDisplay
  - UX.Hide1879
  - UX.GrantFinalGateKey
  - Fancy.GamePlay.ExtendNotesPool
  - Tweaks.TimeSaving.SkipStartupWarning
  - Tweaks.TimeSaving.SkipStartupDelays
  - Fancy.IgnoreCommercialTimeout
  - Utils.ShowNetErrorDetail
  - Tweaks.IgnoreAimeServerError
  - UX.NoAmDaemonAlert
  - Utils.ShowErrorLog
  - GameSettings.ForceAsServer
  - GameSystem.RemoveEncryption

社区功能:
  - GameSystem.VolumeSync
  - Fancy.CustomIntroCinematic
  - Fancy.CustomSkins
  - Fancy.CustomButton
  - Fancy.GamePlay.AlignCircleSlideJudgeDisplay
  - Fancy.GamePlay.SlideArrowAnimation
  - Fancy.GamePlay.SlideFadeInTweak
  - Fancy.GamePlay.SlideLayerReverse
  - UX.JudgeAccuracyInfo
  - Fancy.GamePlay.JudgeDisplay4B
  - UX.FixTrackNumDisplay
  - GameSystem.SoundRouting
  - GameSystem.HeadphoneVolumeMultiply
  - GameSystem.ExteraMouseInput
  - UX.HardwareAlert
  - Fancy.SetFade
  - Fancy.CustomTrackStartDiff
  - Fancy.GamePlay.BreakSlideJudgeBlink
  - Fancy.GamePlay.CustomNoteTypes
  - Fancy.GamePlay.DisableTrackStartTabs
  - Fancy.GamePlay.FanJudgeFlip
  - Fancy.GamePlay.RealisticRandomJudge
  - Fancy.GamePlay.TrackStartProcessTweak
  - Fancy.GamePlay.FixJudgeTouchHoldInNormalArea
  - Fancy.GamePlay.ReviveFinaleVSlide
  - UX.DontRuinMyAccount
  - UX.CustomFnToKeyboard
  - UX.Hide1879
  - UX.GrantFinalGateKey
  - Fancy.GamePlay.TapInHoldFix
  - Tweaks.TimeSaving.CheckSkip
  - Fancy.TrackCamouflage
  - Fancy.ResourcesOverride
  - GameSystem.OldCabLightBoardSupport

