name: AquaMai Build

on:
  workflow_dispatch:
  push:
  pull_request_target:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Fix Git line encoding bug
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Git Describe
        run: |
          $raw = git describe --tags --always
          if ($raw.StartsWith("v")) { $raw = $raw.Substring(1) }
          $parts = $raw.Split('-')
          if ($parts.Length -ge 3) {
            $ver = $parts[0].Split('.')
            $ver[2] = $parts[1]
            $raw = ($ver -join '.') + '-' + $parts[2]
          }
          echo "GIT_DESCRIBE=$raw" >> $env:GITHUB_ENV

      - name: Checkout Assets
        uses: clansty/checkout@main
        with:
          repository: MuNET-OSS/AquaMai-Build-Assets
          ssh-key: ${{ secrets.BUILD_ASSETS_KEY }}
          path: build-assets
          max-attempts: 50
          min-retry-interval: 1
          max-retry-interval: 5

      - name: Build AquaMai
        shell: cmd
        run: |
          copy /y build-assets\SDEZ\* Libs
          powershell ./build.ps1

      - name: Prepare artifact
        shell: cmd
        run: |
          cd Output
          mkdir Upload
          move AquaMai.dll Upload
          move AquaMai.*.toml Upload

      - name: Sign and Upload CI release
        if: github.event_name != 'pull_request_target' && github.ref == 'refs/heads/main'
        shell: cmd
        run: build-assets\Releaser\AquaMaiReleaser.exe "Output\Upload\AquaMai.dll" "${{ env.GIT_DESCRIBE }}"
        env:
          LEGACY_RELEASE_SIGN_PK: ${{ secrets.LEGACY_RELEASE_SIGN_PK }}
          RELEASE_SIGN_V2_PK: ${{ secrets.RELEASE_SIGN_V2_PK }}
          QCLOUD_SECRET_ID: ${{ secrets.QCLOUD_SECRET_ID }}
          QCLOUD_SECRET_KEY: ${{ secrets.QCLOUD_SECRET_KEY }}
          R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
          R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
          VERSION_CONFIG_TOKEN: ${{ secrets.VERSION_CONFIG_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: AquaMai
          path: Output\Upload

      - name: Send to Telegram
        if: github.event_name != 'pull_request_target' && github.ref == 'refs/heads/main'
        run: |
          $Uri = "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMediaGroup"
          $Form = @{
            chat_id = "-1002231087502"
            media = @(
              @{ type = "document"; media = "attach://aquamai_main"; caption = "${{ env.GIT_DESCRIBE }}`n${{ github.event.commits[0].message }}" },
              @{ type = "document"; media = "attach://aquamai_zh" }
              @{ type = "document"; media = "attach://aquamai_en" }
            ) | ConvertTo-Json
            aquamai_main = Get-Item Output\Upload\AquaMai.dll
            aquamai_zh = Get-Item Output\Upload\AquaMai.zh.toml
            aquamai_en = Get-Item Output\Upload\AquaMai.en.toml
          }
          Invoke-RestMethod -Uri $uri -Form $Form -Method Post
